swagger: "2.0"
info:
  version: "0.7.5"
  title: Movie Api
host: localhost:3000
basePath: /
schemes: 
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /movies:
    get:
      description: Returns all movies from the system that the user has access to
      produces:
      - application/json
      responses:
        '200':
          description: A list of movies.
          schema:
            type: array
            item:
              $ref: 'Movies'
      